### ISSUE TITLE
0010 - Quickstart Template sollte aktiv sein nach der Installation

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/uikit_collection#21]
Habe grade das geniale Addon (Version 1.0.1) installiert. Ich denke für den Einsteiger wäre es eine Hilfe, wenn das Quickstart Template direkt aktiv wäre nachdem es installiert wurde.
Wenn gewünscht kann ich vermutlich auch mit einem Pullrequest beitragen.

**Comment by skerbis** [comment]
gerne.

**Comment by dtpop** [comment]
#22
