### ISSUE TITLE
WOOPS wenn Plyr nicht installiert (Ok steht in der Infos.. aber ein WOOPS...)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/uikit_collection#35]
![image](https://user-images.githubusercontent.com/330516/67474635-12d34700-f655-11e9-8926-92f742ea703b.png)

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/uikit_collection/commit/a4e330297a6cf2641f3b0d6c129d901bd37d233d
