### ISSUE TITLE
yform 4.0.2

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/uikit_collection#63]
das uikit-ytemplate scheint nicht an die richtige stelle kopiert zu werden. nach update auf YF 4.0.2. schmiss es mir whoops "Path cannot be empty". im ytemplates-ordner unter yform-plugins-manager war nur der ordner „bootstrap“. uikit–collection hatte ich auch schon neu installiert, trotzdem musste ich dann den uikit-ytemplate-ordner händisch in den y-template-ordner kopieren.

**Comment by skerbis** [comment]
Die Templates werden nirgends hin kopiert.

**Comment by ansichtsache** [comment]
ok, danke fürs schauen.
