### ISSUE TITLE
Beispiel-Templates und Module

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/uikit_collection#64]
Hi, in der Hilfe etc wird ein Verweis auf die Modulsammung gemacht. Ein paar Beispiel-Module und -Templates wären super. Soweit ich das erkennen kann, werden mit diesem Modul nur im Backend die CSS Assets eingebunden?

**Comment by skerbis** [comment]
Das ist korrekt. Demo Module und Templates finden sich in der Uikit3-Demo, das auf dieses AddOn aufbaut.
