### ISSUE TITLE
basis backend UIkit liefern

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/uikit_collection#8]

**Comment by alexplusde** [comment]
Wäre es vielleicht sinnvoll, im Backend weiter mit Bootstrap zu arbeiten, da ja nur Informationen ausgegeben werden müssen und keine Interaktion stattfindet...

**Comment by skerbis** [comment]
Sehe ich anders. Ich finde, der Redakteur sollte auch im Backend sehen können was er gebastelt hat.

**Comment by skerbis** [comment]
Bleibt erstmal so.
